# Generated by Django 5.1.2 on 2024-10-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=50)),
                ('Confirm_password', models.CharField(max_length=50)),
                ('my_location_link', models.URLField(blank=True, null=True)),
                ('whatsapp_number', models.CharField(max_length=10)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.login')),
            ],
        ),
    ]
