# Generated by Django 5.1.2 on 2024-10-30 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_brand_oiltype_carforsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarForRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rent_car_image', models.ImageField(blank=True, null=True, upload_to='car_images/rent/')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.brand')),
                ('oil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.oiltype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.user')),
            ],
        ),
    ]
