# Generated by Django 5.1.2 on 2024-10-30 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_carforrent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Confirm_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
    ]
